# ------------------------------------------------------------------------------
#
# make_variable_selection_output.R
#
# This file handles exporting the covariate sets generated by eaqch variable
# selection method
#
# Arguments:
#  - name - string, specifies outcome
#  - cohort - string, defines which of three opensafely cohorts to describe
#             (prevax, vax, unvax)
#  - preex - boolean/string, defines preexisting conditions
#            for the replication preex = FALSE always
#            ("All", TRUE, or FALSE)
#
# Returns:
#  - CSV summarising variable sets selected by LASSO, LASSO_X and LASSO_union
#
# Authors: Emma Tarmey
#
# ------------------------------------------------------------------------------


# Load libraries ---------------------------------------------------------------
print("Load libraries")

library(magrittr)
library(here)
library(dplyr)


# Specify arguments ------------------------------------------------------------
print("Specify arguments")

args <- commandArgs(trailingOnly = TRUE)

print(length(args))

if (length(args) == 0) {
  # default argument values
  name    <- "cohort_prevax-main-ami"
  cohort  <- "prevax"
  preex   <- FALSE
} else {
  # YAML arguments
  name    <- args[[1]]
  cohort  <- args[[2]]

  # optional argument
  if (length(args) < 4) {
    preex <- "All"
  } else {
    preex <- args[[4]]
  } # allow an empty input for the preex variable
}

preex_string <- ""

# Define variable set output folder ---------------------------------------
print("Creating output folder")

# setting up the sub directory
makeout_dir <- "output/make_output/"

# check if sub directory exists, create if not
fs::dir_create(here::here(makeout_dir))


# Load variable sets and data ---------------------------------------------
print("Load variable sets and data")

# subsample
model_input_df <- readr::read_rds(paste0(
  "output/model/model_input_subsample-",
  name,
  ".rds"
))

lasso_vars_selected <- union( read.csv(
  paste0(
    "output/lasso_var_selection/lasso_var_selection-",
    name,
    ".csv"
))[, 'x'], c("cov_cat_sex", "cov_num_age"))

lasso_X_vars_selected <- union( read.csv(
  paste0(
    "output/lasso_X_var_selection/lasso_X_var_selection-",
    name,
    ".csv"
))[, 'x'], c("cov_cat_sex", "cov_num_age"))

lasso_union_vars_selected <- union( read.csv(
  paste0(
    "output/lasso_union_var_selection/lasso_union_var_selection-",
    name,
    ".csv"
))[, 'x'], c("cov_cat_sex", "cov_num_age"))


# Initialise and populate data frame -------------------------------------
print("Initialise and populate data frame")

model_input_df$binary_outcome          <- !is.na(model_input_df$out_date)
model_input_df$binary_covid19_exposure <- !is.na(model_input_df$exp_date)

model_input_df <- (model_input_df %>% select(!c(
  patient_id, index_date,                                  # admin
  binary_outcome, out_date, end_date_outcome, cov_bin_ami, # outcome
  exp_date                                                 # remove unnecessary
)))

all_vars_names         <- colnames(model_input_df)
lasso_vars_names       <- lasso_vars_selected
lasso_X_vars_names     <- lasso_X_vars_selected
lasso_union_vars_names <- lasso_union_vars_selected

total_num_vars            <- length(all_vars_names)
lasso_selected_vars       <- length(lasso_vars_names)
lasso_X_selected_vars     <- length(lasso_X_vars_names)
lasso_union_selected_vars <- length(lasso_union_vars_names)

methods        <- c("Fully-adjusted", "Lasso", "Lasso_X", "Lasso_union")
available_vars <- c(
  total_num_vars,
  total_num_vars,
  total_num_vars - 1, # Lasso_X has exposure as response, not as explanatory
  total_num_vars
)
selected_vars  <- c(
  total_num_vars,
  lasso_selected_vars,
  lasso_X_selected_vars,
  lasso_union_selected_vars
)

vars_list <- c(
  paste(all_vars_names, collapse=';'),
  paste(lasso_vars_names, collapse=';'),
  paste(lasso_X_vars_names, collapse=';'),
  paste(lasso_union_vars_names, collapse=';')
)

results <- data.frame(
  methods        = methods,
  available_vars = available_vars,
  selected_vars  = selected_vars,
  vars_list      = vars_list
)


# Save results ----------------------------------------------------
print("Save results")

write.csv(
  results,
  paste0(makeout_dir, "variable_selection-", name, preex_string, ".csv"),
  row.names = FALSE
)
